//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cms.Admin.Web.ServiceProvider {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/Cms.DomainObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cms.Admin.Web.ServiceProvider.CreateAdminAcctResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cms.Admin.Web.ServiceProvider.LoginResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateAdminAcctResponse", Namespace="http://schemas.datacontract.org/2004/07/Cms.DomainObjects")]
    [System.SerializableAttribute()]
    public partial class CreateAdminAcctResponse : Cms.Admin.Web.ServiceProvider.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/Cms.DomainObjects")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : Cms.Admin.Web.ServiceProvider.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProvider.IAdminServiceApi")]
    public interface IAdminServiceApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminServiceApi/AdminLogin", ReplyAction="http://tempuri.org/IAdminServiceApi/AdminLoginResponse")]
        Cms.Admin.Web.ServiceProvider.LoginResponse AdminLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminServiceApi/AdminLogin", ReplyAction="http://tempuri.org/IAdminServiceApi/AdminLoginResponse")]
        System.Threading.Tasks.Task<Cms.Admin.Web.ServiceProvider.LoginResponse> AdminLoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminServiceApi/CreateAdminAccount", ReplyAction="http://tempuri.org/IAdminServiceApi/CreateAdminAccountResponse")]
        Cms.Admin.Web.ServiceProvider.CreateAdminAcctResponse CreateAdminAccount(string orgName, string username, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminServiceApi/CreateAdminAccount", ReplyAction="http://tempuri.org/IAdminServiceApi/CreateAdminAccountResponse")]
        System.Threading.Tasks.Task<Cms.Admin.Web.ServiceProvider.CreateAdminAcctResponse> CreateAdminAccountAsync(string orgName, string username, string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceApiChannel : Cms.Admin.Web.ServiceProvider.IAdminServiceApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceApiClient : System.ServiceModel.ClientBase<Cms.Admin.Web.ServiceProvider.IAdminServiceApi>, Cms.Admin.Web.ServiceProvider.IAdminServiceApi {
        
        public AdminServiceApiClient() {
        }
        
        public AdminServiceApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cms.Admin.Web.ServiceProvider.LoginResponse AdminLogin(string username, string password) {
            return base.Channel.AdminLogin(username, password);
        }
        
        public System.Threading.Tasks.Task<Cms.Admin.Web.ServiceProvider.LoginResponse> AdminLoginAsync(string username, string password) {
            return base.Channel.AdminLoginAsync(username, password);
        }
        
        public Cms.Admin.Web.ServiceProvider.CreateAdminAcctResponse CreateAdminAccount(string orgName, string username, string email, string password) {
            return base.Channel.CreateAdminAccount(orgName, username, email, password);
        }
        
        public System.Threading.Tasks.Task<Cms.Admin.Web.ServiceProvider.CreateAdminAcctResponse> CreateAdminAccountAsync(string orgName, string username, string email, string password) {
            return base.Channel.CreateAdminAccountAsync(orgName, username, email, password);
        }
    }
}
